name: Nathan Falkenborg
favicon: null
layout_spectrum: 0.5576490701641887
typography_spectrum: 0.5759212574921548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8553597445134073
  lightness: 0.05907882493920624
  saturation: 0.20923205511644483
  rhythmicContrast: 0.4064014710020274
purpose: []
